version: '3.4'

services:
  dotnetapi-boilerplate:
    image: dotnetapi-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dotnetapi-boilerplate.pfx
    volumes:
      - ~/.aspnet/https:/https:ro